version: "3"
services:
  proxy:
    image: haproxy:1.7-alpine
    ports:
      - 8000:6301
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - myapp
  db:
    container_name: mysql
    image: mysql
    env_file:
      - .env
    volumes:
      - ./data/db_data:/var/lib/mysql
    ports:
      - 33306:3306
    networks:
      - myapp
  nginx_master:
    container_name: my_nginx_master
    build: 
        context: ./nginx
        dockerfile: ./Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/keepalived/master.conf:/etc/keepalived/keepalived.conf
      - ./nginx/favicon.ico:/var/www/favicon.ico
    networks:
      myapp:
        ipv4_address: 172.20.128.2
    cap_add: 
      - NET_ADMIN
  nginx_slave:
    container_name: my_nginx_slave
    build: 
        context: ./nginx
        dockerfile: ./Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/keepalived/slave.conf:/etc/keepalived/keepalived.conf
      - ./nginx/favicon.ico:/var/www/favicon.ico
    networks:
      myapp:
        ipv4_address: 172.20.128.3
    cap_add: 
      - NET_ADMIN
  uwsgi_1:
    container_name: my_uwsgi_1
    build:
      context: ./
      dockerfile: ./uwsgi/Dockerfile
    command: uwsgi /uwsgi.ini --py-autoreload 3
    volumes:
      - ./:/usr/src/app
      - ./uwsgi/uwsgi.ini:/uwsgi.ini
    networks:
      - myapp
  uwsgi_2:
    container_name: my_uwsgi_2
    build:
      context: ./
      dockerfile: ./uwsgi/Dockerfile
    command: uwsgi /uwsgi.ini --py-autoreload 3
    volumes:
      - ./:/usr/src/app
      - ./uwsgi/uwsgi.ini:/uwsgi.ini
    networks:
      - myapp
  uwsgi_3:
    container_name: my_uwsgi_3
    build:
      context: ./
      dockerfile: ./uwsgi/Dockerfile
    command: uwsgi /uwsgi.ini --py-autoreload 3
    volumes:
      - ./:/usr/src/app
      - ./uwsgi/uwsgi.ini:/uwsgi.ini
    networks:
      - myapp
      
networks:
  myapp:
    ipam:
      config:
        - subnet: 172.20.0.0/16
